### ISSUE TITLE
Inject CSS in 'head' instead of 'head-footer'?

### ISSUE THREAD

**Issue by simonihmig** [Vestorly/ember-cli-preloader#7]
Is there a good reason why the preloader CSS is injected into the `content-for` 'head-footer' hook instead of the 'head' hook?

head-footer comes after vendor.css and frontend.css, and it seams that the preloader css is evaluated only after those two css files are fully loaded. That means the preloader does not appear immediately, but only after loading the other css files, which defeats the purpose of the preloader...

I tested it with the head hook, and it worked as expected then! Can file a PR if needed, though it's only a little change in `index.js`.

**Comment by simonihmig** [comment]
I guess you can ignore this issue, must had some local caching issues. The preloader gets displayed after all css is loaded in either way. You would probably have to inject the normal css asynchronously by JS in some way to prevent waiting for it to load. Closing this, sorry for the confusion!

**Comment by joebartels** [comment]
yeah everything in the `<body></body>` won't be shown until everything in the `<head></head>` tag is fetched. (except for scripts with an `async` attribute).

You might be on to something. Oerhaps there could be JS in the `<head></head>` that adds the preloader... not sure the order of events in that case -worth trying!
